// Compact in-browser mirror of the seeded workout_blocks library, so the /demo
// page can generate a full, real plan with zero backend. Kept in sync with
// supabase/seed/0002_workout_blocks.sql in spirit (a representative subset).
import type { WorkoutBlock } from "@/lib/engine";

export const DEMO_LIBRARY: WorkoutBlock[] = [
  { id: "wu_general_raise", block_type: "warmup", station: "general",
    content: [{ exercise: "Row easy", distance_m: 500 }, { exercise: "World's greatest stretch", reps: 8 }, { exercise: "Air squats", reps: 15 }],
    equipment_variant: "gym", difficulty_tier: 1, session_types: ["strength", "station_work", "run_intervals", "compromised_run", "full_sim", "benchmark"], tags: ["warmup"] },
  { id: "wu_run_drills", block_type: "warmup", station: "run",
    content: [{ exercise: "Easy jog", distance_m: 800 }, { exercise: "A-skips", distance_m: 20, sets: 3 }, { exercise: "Strides", distance_m: 60, sets: 4 }],
    equipment_variant: "gym", difficulty_tier: 1, session_types: ["run_easy", "run_intervals", "compromised_run"], tags: ["warmup"] },

  // ── The four core run sessions, in their variants (runVariants.ts picks) ──
  { id: "lr_flat_steady", block_type: "main", station: "run",
    content: [{ exercise: "Continuous Zone-2 run on flat terrain — conversational, heart rate strictly in Z2" }],
    equipment_variant: "gym", difficulty_tier: 1, session_types: ["run_easy"], tags: ["aerobic", "long", "flat"] },
  { id: "lr_rolling_hills", block_type: "main", station: "run",
    content: [{ exercise: "Rolling-hills run: drop the pace (or walk) on every climb to hold Zone 2" }, { exercise: "Let the descents stay relaxed — no braking, no surging" }],
    equipment_variant: "gym", difficulty_tier: 2, session_types: ["run_easy"], tags: ["aerobic", "long", "hills"] },
  { id: "lr_progression", block_type: "main", station: "run",
    content: [{ exercise: "Strict Zone 2 for the first two thirds" }, { exercise: "Final third: lift progressively to the top of Zone 3 (sub-threshold)" }],
    equipment_variant: "gym", difficulty_tier: 3, session_types: ["run_easy"], tags: ["aerobic", "long", "progression"] },

  { id: "er_shakeout_strides", block_type: "main", station: "run",
    content: [{ exercise: "Very easy jog, Zone 1 to low Zone 2" }, { exercise: "Strides, relaxed and fast — not a sprint", distance_m: 80, sets: 5, rest_sec: 60 }],
    equipment_variant: "gym", difficulty_tier: 1, session_types: ["run_easy"], tags: ["recovery", "strides"] },
  { id: "er_soft_surface", block_type: "main", station: "run",
    content: [{ exercise: "Recovery run on grass or forest floor at RPE 1-3 — soft surface, short stride, no watch-watching" }],
    equipment_variant: "gym", difficulty_tier: 1, session_types: ["run_easy"], tags: ["recovery", "soft_surface"] },
  { id: "er_cross_combo", block_type: "main", station: "run",
    content: [{ exercise: "Easy running, Zone 1" }, { exercise: "SkiErg, RowErg or bike in Zone 1 — same aerobic time, half the impact" }],
    equipment_variant: "gym", difficulty_tier: 1, session_types: ["run_easy"], tags: ["recovery", "cross_training", "erg"] },

  { id: "iv_vo2_1k", block_type: "main", station: "run",
    content: [{ exercise: "1000 m at 3k-5k race pace", distance_m: 1000, sets: 6, rest_sec: 135 }],
    equipment_variant: "gym", difficulty_tier: 2, session_types: ["run_intervals"], tags: ["vo2", "intervals"] },
  { id: "iv_cruise_2k", block_type: "main", station: "run",
    content: [{ exercise: "2000 m at 10k / half-marathon pace", distance_m: 2000, sets: 4, rest_sec: 75 }],
    equipment_variant: "gym", difficulty_tier: 2, session_types: ["run_intervals"], tags: ["threshold", "intervals"] },
  { id: "iv_pyramid", block_type: "main", station: "run",
    content: [{ exercise: "400 m at 3k pace", distance_m: 400, rest_sec: 75 }, { exercise: "800 m at 5k pace", distance_m: 800, rest_sec: 150 }, { exercise: "1200 m at 5k-10k pace", distance_m: 1200, rest_sec: 225 }, { exercise: "1600 m at 10k pace", distance_m: 1600, rest_sec: 300 }, { exercise: "1200 m at 5k-10k pace", distance_m: 1200, rest_sec: 225 }, { exercise: "800 m at 5k pace", distance_m: 800, rest_sec: 150 }, { exercise: "400 m at 3k pace", distance_m: 400, rest_sec: 75 }],
    equipment_variant: "gym", difficulty_tier: 3, session_types: ["run_intervals"], tags: ["vo2", "intervals", "pyramid"] },
  { id: "iv_30_30", block_type: "main", station: "run",
    content: [{ exercise: "10-minute block: 30 s hard (Zone 5) / 30 s jog (Zone 1-2)", sets: 3, rest_sec: 180 }],
    equipment_variant: "gym", difficulty_tier: 2, session_types: ["run_intervals"], tags: ["vo2", "anaerobic", "intervals", "short_reps"] },

  { id: "cr_sled_brick", block_type: "main", station: "sled_push",
    content: [{ exercise: "Heavy sled push", distance_m: 50, load_by_division: { open: "125 kg total", pro: "175 kg total" }, sets: 5, rest_sec: 0 }, { exercise: "800 m run at Hyrox target pace, straight off the sled", distance_m: 800, sets: 5, rest_sec: 180 }],
    equipment_variant: "gym", difficulty_tier: 2, session_types: ["compromised_run"], tags: ["compromised", "sled", "legs"] },
  { id: "cr_lactate_flush", block_type: "main", station: "row",
    content: [{ exercise: "1000 m RowErg or SkiErg at hard race pace", distance_m: 1000, sets: 4, rest_sec: 0 }, { exercise: "1000 m run at controlled threshold pace (Zone 4)", distance_m: 1000, sets: 4, rest_sec: 180 }],
    equipment_variant: "gym", difficulty_tier: 3, session_types: ["compromised_run"], tags: ["compromised", "erg", "upper_body"] },
  { id: "cr_heavy_legs", block_type: "main", station: "sandbag_lunges",
    content: [{ exercise: "Walking lunges", distance_m: 100, load_by_division: { open: "10 kg sandbag", pro: "20 kg sandbag" }, sets: 3, rest_sec: 0 }, { exercise: "1200 m run — first 400 m buffered, last 800 m at race pace", distance_m: 1200, sets: 3, rest_sec: 240 }],
    equipment_variant: "gym", difficulty_tier: 3, session_types: ["compromised_run"], tags: ["compromised", "lunges", "legs"] },
  { id: "cr_micro_sim", block_type: "main", station: "general",
    content: [{ exercise: "Round 1: Sled pull, then 1000 m at goal race pace", distance_m: 1000, rest_sec: 120 }, { exercise: "Round 2: Burpee broad jumps, then 1000 m at goal race pace", distance_m: 1000, rest_sec: 120 }, { exercise: "Round 3: Farmers carry, then 1000 m at goal race pace", distance_m: 1000, rest_sec: 120 }, { exercise: "Round 4: Wall balls, then 1000 m at goal race pace", distance_m: 1000, rest_sec: 0 }],
    equipment_variant: "gym", difficulty_tier: 3, session_types: ["compromised_run"], tags: ["compromised", "simulation", "pacing"] },

  // ── Station sessions, in their variants (stationVariants.ts picks) ──────
  { id: "sv_overload_sled_grip", block_type: "main", station: "sled_push",
    content: [{ exercise: "Sled push at 125% of race weight", distance_m: 25, load_by_division: { open: "155 kg total", pro: "220 kg total" }, sets: 5, rest_sec: 0 }, { exercise: "Heavy farmers carry (+20% of race weight), straight off the sled", distance_m: 100, load_by_division: { open: "2x28 kg", pro: "2x38 kg" }, sets: 5, rest_sec: 150 }],
    equipment_variant: "gym", difficulty_tier: 3, session_types: ["station_work", "strength"], tags: ["sled", "grip", "overload", "base"] },
  { id: "sv_aerobic_erg_capacity", block_type: "main", station: "ski_erg",
    content: [{ exercise: "SkiErg at Z2 / low Z3 (about 2:05-2:10 per 500 m)", sets: 5, rest_sec: 0 }, { exercise: "RowErg at the same effort, straight over — no pause between the ergs", sets: 5, rest_sec: 0 }],
    equipment_variant: "gym", difficulty_tier: 1, session_types: ["station_work"], tags: ["ski", "row", "erg", "aerobic", "base"] },
  { id: "sv_wallball_lunge_volume", block_type: "main", station: "wall_balls",
    content: [{ exercise: "Wall balls, unbroken", reps: 25, load_by_division: { open: "6-7 kg / 3.0 m target", pro: "9-10 kg / 3.0 m target" }, sets: 5, rest_sec: 0 }, { exercise: "Walking lunges, kettlebells in the front rack", reps: 20, load_by_division: { open: "2x16 kg", pro: "2x24 kg" }, sets: 5, rest_sec: 90 }],
    equipment_variant: "gym", difficulty_tier: 2, session_types: ["station_work", "strength"], tags: ["wallball", "lunges", "volume", "base"] },

  { id: "sv_erg_threshold", block_type: "main", station: "row",
    content: [{ exercise: "1000 m SkiErg or RowErg at race pace minus 3-5 s per 500 m (about 1:48-1:52), stroke rate 26-30", distance_m: 1000, sets: 5, rest_sec: 90 }],
    equipment_variant: "gym", difficulty_tier: 3, session_types: ["station_work"], tags: ["erg", "threshold", "build"] },
  { id: "sv_density_emom", block_type: "main", station: "general",
    content: [{ exercise: "Minute 1: wall balls, unbroken", reps: 15, load_by_division: { open: "6 kg / 3.0 m", pro: "9 kg / 3.0 m" }, sets: 6 }, { exercise: "Minute 2: burpee broad jumps, smooth rhythm", reps: 12, sets: 6 }, { exercise: "Minute 3: farmers carry at race weight", distance_m: 50, load_by_division: { open: "2x24 kg", pro: "2x32 kg" }, sets: 6 }, { exercise: "Minute 4: SkiErg at sub-max pace", distance_m: 250, sets: 6 }, { exercise: "Minute 5: rest", sets: 6 }],
    equipment_variant: "gym", difficulty_tier: 2, session_types: ["station_work"], tags: ["emom", "density", "build"] },
  { id: "sv_push_pull_circuit", block_type: "main", station: "sled_pull",
    content: [{ exercise: "Sled push at race weight", distance_m: 50, load_by_division: { open: "125 kg total", pro: "175 kg total" }, sets: 4, rest_sec: 0 }, { exercise: "Sled pull at race weight, straight over", distance_m: 50, load_by_division: { open: "78 kg total", pro: "128 kg total" }, sets: 4, rest_sec: 0 }, { exercise: "Dumbbell thrusters", reps: 20, load_by_division: { open: "2x15 kg", pro: "2x22.5 kg" }, sets: 4, rest_sec: 180 }],
    equipment_variant: "gym", difficulty_tier: 3, session_types: ["station_work", "strength"], tags: ["sled", "legs", "lactate", "build"] },

  { id: "sv_engine_gauntlet", block_type: "main", station: "general",
    content: [{ exercise: "SkiErg", distance_m: 1000 }, { exercise: "Sled push at race weight", distance_m: 50, load_by_division: { open: "125 kg total", pro: "175 kg total" } }, { exercise: "Sled pull at race weight", distance_m: 50, load_by_division: { open: "78 kg total", pro: "128 kg total" } }, { exercise: "Burpee broad jumps", distance_m: 80 }, { exercise: "RowErg", distance_m: 1000 }, { exercise: "Farmers carry at race weight", distance_m: 200, load_by_division: { open: "2x24 kg", pro: "2x32 kg" } }, { exercise: "Sandbag lunges at race weight", distance_m: 100, load_by_division: { open: "20 kg", pro: "30 kg" } }, { exercise: "Wall balls", reps: 100, load_by_division: { open: "6 kg / 3.0 m", pro: "9 kg / 3.0 m" } }],
    equipment_variant: "gym", difficulty_tier: 3, session_types: ["station_work"], tags: ["chipper", "race_pace", "specificity"] },
  { id: "sv_station_intervals_3x3", block_type: "main", station: "general",
    content: [{ exercise: "RowErg at race pace", distance_m: 500, sets: 3 }, { exercise: "Sled push", distance_m: 25, load_by_division: { open: "125 kg total", pro: "175 kg total" }, sets: 3 }, { exercise: "Burpee broad jumps", reps: 30, sets: 3 }, { exercise: "Sandbag lunges", distance_m: 50, load_by_division: { open: "20 kg", pro: "30 kg" }, sets: 3 }, { exercise: "Wall balls", reps: 30, load_by_division: { open: "6 kg / 3.0 m", pro: "9 kg / 3.0 m" }, sets: 3, rest_sec: 180 }],
    equipment_variant: "gym", difficulty_tier: 3, session_types: ["station_work"], tags: ["simulation", "transitions", "specificity"] },
  { id: "sv_race_finish_finisher", block_type: "main", station: "wall_balls",
    content: [{ exercise: "Sandbag walking lunges at race weight", distance_m: 25, load_by_division: { open: "20 kg", pro: "30 kg" }, sets: 4, rest_sec: 0 }, { exercise: "Wall balls, unbroken", reps: 25, load_by_division: { open: "6 kg / 3.0 m", pro: "9 kg / 3.0 m" }, sets: 4, rest_sec: 60 }],
    equipment_variant: "gym", difficulty_tier: 3, session_types: ["station_work"], tags: ["wallball", "lunges", "finisher", "specificity"] },

  { id: "sv_neural_priming", block_type: "main", station: "general",
    content: [{ exercise: "SkiErg at exact race pace", distance_m: 250, sets: 3 }, { exercise: "Sled push at race weight — fast and explosive, not heavy", distance_m: 12.5, load_by_division: { open: "125 kg total", pro: "175 kg total" }, sets: 3 }, { exercise: "Burpee broad jumps for maximum distance, soft landings", reps: 5, sets: 3 }, { exercise: "Wall balls at race weight", reps: 10, load_by_division: { open: "6 kg / 3.0 m", pro: "9 kg / 3.0 m" }, sets: 3, rest_sec: 120 }],
    equipment_variant: "gym", difficulty_tier: 1, session_types: ["station_work"], tags: ["priming", "taper", "race_week"] },
  { id: "sv_movement_primer", block_type: "main", station: "row",
    content: [{ exercise: "Easy Zone-1 warm-up" }, { exercise: "250 m RowErg or SkiErg with 30 s at race pace inside each", distance_m: 250, sets: 4, rest_sec: 90 }, { exercise: "Mobility for shoulder girdle and hip flexors" }],
    equipment_variant: "gym", difficulty_tier: 1, session_types: ["station_work"], tags: ["priming", "mobility", "taper", "race_week"] },

  { id: "st_ski_intervals", block_type: "main", station: "ski_erg",
    content: [{ exercise: "SkiErg intervals", distance_m: 250, sets: 6, rest_sec: 60 }],
    equipment_variant: "gym", difficulty_tier: 1, session_types: ["station_work"], tags: ["ski"] },
  { id: "st_ski_race", block_type: "main", station: "ski_erg",
    content: [{ exercise: "SkiErg race-pace holds", distance_m: 500, sets: 4, rest_sec: 90 }],
    equipment_variant: "gym", difficulty_tier: 2, session_types: ["station_work"], tags: ["ski"] },
  { id: "st_row_intervals", block_type: "main", station: "row",
    content: [{ exercise: "Row intervals", distance_m: 250, sets: 6, rest_sec: 60 }],
    equipment_variant: "gym", difficulty_tier: 1, session_types: ["station_work"], tags: ["row"] },
  { id: "st_sled_push", block_type: "main", station: "sled_push",
    content: [{ exercise: "Sled push", distance_m: 12.5, load_by_division: { open: "125 kg total", pro: "175 kg total" }, sets: 6, rest_sec: 90 }],
    equipment_variant: "gym", difficulty_tier: 2, session_types: ["station_work", "strength"], tags: ["sled"] },
  { id: "st_sled_pull", block_type: "main", station: "sled_pull",
    content: [{ exercise: "Sled pull", distance_m: 12.5, load_by_division: { open: "78 kg total", pro: "128 kg total" }, sets: 6, rest_sec: 90 }],
    equipment_variant: "gym", difficulty_tier: 2, session_types: ["station_work", "strength"], tags: ["sled"] },
  { id: "st_burpee_bj", block_type: "main", station: "burpee_broad_jump",
    content: [{ exercise: "Burpee broad jumps", distance_m: 20, sets: 4, rest_sec: 75 }],
    equipment_variant: "gym", difficulty_tier: 1, session_types: ["station_work"], tags: ["burpee"] },
  { id: "st_farmers", block_type: "main", station: "farmers_carry",
    content: [{ exercise: "Farmers carry", distance_m: 100, load_by_division: { open: "2x24 kg", pro: "2x32 kg" }, sets: 4, rest_sec: 90 }],
    equipment_variant: "gym", difficulty_tier: 2, session_types: ["station_work", "strength"], tags: ["grip"] },
  { id: "st_lunges", block_type: "main", station: "sandbag_lunges",
    content: [{ exercise: "Sandbag walking lunges", distance_m: 50, load_by_division: { open: "20 kg", pro: "30 kg" }, sets: 4, rest_sec: 90 }],
    equipment_variant: "gym", difficulty_tier: 2, session_types: ["station_work", "strength"], tags: ["legs"] },
  { id: "st_wallballs", block_type: "main", station: "wall_balls",
    content: [{ exercise: "Wall balls (unbroken sets)", reps: 25, load_by_division: { open: "6 kg / 3.0 m", pro: "9 kg / 3.0 m" }, sets: 4, rest_sec: 75 }],
    equipment_variant: "gym", difficulty_tier: 1, session_types: ["station_work"], tags: ["wallball"] },

  { id: "str_lower_squat", block_type: "main", station: "general",
    content: [{ exercise: "Back squat", sets: 4, reps: 6, load_by_division: { open: "70% 1RM", pro: "78% 1RM" }, rest_sec: 150 }, { exercise: "Romanian deadlift", sets: 3, reps: 8, rest_sec: 120 }],
    equipment_variant: "gym", difficulty_tier: 2, session_types: ["strength"], tags: ["lower"] },
  { id: "str_push_pull", block_type: "main", station: "general",
    content: [{ exercise: "Push press", sets: 4, reps: 6, rest_sec: 120 }, { exercise: "Pull-ups", sets: 4, reps: 8, rest_sec: 90 }],
    equipment_variant: "gym", difficulty_tier: 2, session_types: ["strength"], tags: ["upper"] },

  { id: "sim_full_hyrox", block_type: "main", station: "general",
    content: [{ exercise: "Full Hyrox simulation: 8x(1000 m run + station)", distance_m: 8000, sets: 1, load_by_division: { open: "all stations @ open", pro: "all stations @ pro" } }],
    equipment_variant: "gym", difficulty_tier: 3, session_types: ["full_sim", "benchmark"], tags: ["simulation"] },
  { id: "sim_half_hyrox", block_type: "main", station: "general",
    content: [{ exercise: "4 rounds: 1000 m run + one station", distance_m: 1000, sets: 4, load_by_division: { open: "open weights", pro: "pro weights" } }],
    equipment_variant: "gym", difficulty_tier: 2, session_types: ["full_sim"], tags: ["simulation"] },

  { id: "mob_lower", block_type: "mobility", station: "general",
    content: [{ exercise: "Couch stretch", reps: 60, sets: 2 }, { exercise: "90/90 hip switches", reps: 10, sets: 2 }],
    equipment_variant: "gym", difficulty_tier: 1, session_types: ["mobility", "strength", "station_work", "compromised_run", "run_intervals", "full_sim"], tags: ["mobility"] },
  { id: "mob_full", block_type: "mobility", station: "general",
    content: [{ exercise: "Thoracic openers", reps: 10, sets: 2 }, { exercise: "Pigeon stretch", reps: 45, sets: 2 }],
    equipment_variant: "gym", difficulty_tier: 1, session_types: ["mobility"], tags: ["mobility"] },
];
