// Compact in-browser mirror of the seeded workout_blocks library, so the /demo
// page can generate a full, real plan with zero backend. Kept in sync with
// supabase/seed/0002_workout_blocks.sql in spirit (a representative subset).
import type { WorkoutBlock } from "@/lib/engine";

export const DEMO_LIBRARY: WorkoutBlock[] = [
  { id: "wu_general_raise", block_type: "warmup", station: "general",
    content: [{ exercise: "Row easy", distance_m: 500 }, { exercise: "World's greatest stretch", reps: 8 }, { exercise: "Air squats", reps: 15 }],
    equipment_variant: "gym", difficulty_tier: 1, session_types: ["strength", "station_work", "run_intervals", "compromised_run", "full_sim", "benchmark"], tags: ["warmup"] },
  { id: "wu_run_drills", block_type: "warmup", station: "run",
    content: [{ exercise: "Easy jog", distance_m: 800 }, { exercise: "A-skips", distance_m: 20, sets: 3 }, { exercise: "Strides", distance_m: 60, sets: 4 }],
    equipment_variant: "gym", difficulty_tier: 1, session_types: ["run_easy", "run_intervals", "compromised_run"], tags: ["warmup"] },

  { id: "run_easy_z2", block_type: "main", station: "run",
    content: [{ exercise: "Zone-2 continuous run", distance_m: 6000 }],
    equipment_variant: "gym", difficulty_tier: 1, session_types: ["run_easy"], tags: ["aerobic"] },
  { id: "run_intervals_400", block_type: "main", station: "run",
    content: [{ exercise: "400 m at interval pace", sets: 6, distance_m: 400, rest_sec: 90 }],
    equipment_variant: "gym", difficulty_tier: 1, session_types: ["run_intervals"], tags: ["vo2"] },
  { id: "run_intervals_1k", block_type: "main", station: "run",
    content: [{ exercise: "1000 m at tempo pace", sets: 5, distance_m: 1000, rest_sec: 150 }],
    equipment_variant: "gym", difficulty_tier: 3, session_types: ["run_intervals"], tags: ["threshold"] },

  { id: "cr_run_wallball", block_type: "main", station: "general",
    content: [{ exercise: "1000 m run at race pace", distance_m: 1000, sets: 4 }, { exercise: "Wall balls after each run", reps: 25, load_by_division: { open: "6 kg", pro: "9 kg" }, sets: 4, rest_sec: 120 }],
    equipment_variant: "gym", difficulty_tier: 1, session_types: ["compromised_run"], tags: ["compromised"] },
  { id: "cr_run_sled", block_type: "main", station: "general",
    content: [{ exercise: "800 m run at race pace", distance_m: 800, sets: 4 }, { exercise: "Sled push 15 m", distance_m: 15, load_by_division: { open: "125 kg total", pro: "175 kg total" }, sets: 4, rest_sec: 150 }],
    equipment_variant: "gym", difficulty_tier: 2, session_types: ["compromised_run"], tags: ["compromised"] },

  { id: "st_ski_intervals", block_type: "main", station: "ski_erg",
    content: [{ exercise: "SkiErg intervals", distance_m: 250, sets: 6, rest_sec: 60 }],
    equipment_variant: "gym", difficulty_tier: 1, session_types: ["station_work"], tags: ["ski"] },
  { id: "st_ski_race", block_type: "main", station: "ski_erg",
    content: [{ exercise: "SkiErg race-pace holds", distance_m: 500, sets: 4, rest_sec: 90 }],
    equipment_variant: "gym", difficulty_tier: 2, session_types: ["station_work"], tags: ["ski"] },
  { id: "st_row_intervals", block_type: "main", station: "row",
    content: [{ exercise: "Row intervals", distance_m: 250, sets: 6, rest_sec: 60 }],
    equipment_variant: "gym", difficulty_tier: 1, session_types: ["station_work"], tags: ["row"] },
  { id: "st_sled_push", block_type: "main", station: "sled_push",
    content: [{ exercise: "Sled push", distance_m: 12.5, load_by_division: { open: "125 kg total", pro: "175 kg total" }, sets: 6, rest_sec: 90 }],
    equipment_variant: "gym", difficulty_tier: 2, session_types: ["station_work", "strength"], tags: ["sled"] },
  { id: "st_sled_pull", block_type: "main", station: "sled_pull",
    content: [{ exercise: "Sled pull", distance_m: 12.5, load_by_division: { open: "78 kg total", pro: "128 kg total" }, sets: 6, rest_sec: 90 }],
    equipment_variant: "gym", difficulty_tier: 2, session_types: ["station_work", "strength"], tags: ["sled"] },
  { id: "st_burpee_bj", block_type: "main", station: "burpee_broad_jump",
    content: [{ exercise: "Burpee broad jumps", distance_m: 20, sets: 4, rest_sec: 75 }],
    equipment_variant: "gym", difficulty_tier: 1, session_types: ["station_work"], tags: ["burpee"] },
  { id: "st_farmers", block_type: "main", station: "farmers_carry",
    content: [{ exercise: "Farmers carry", distance_m: 100, load_by_division: { open: "2x24 kg", pro: "2x32 kg" }, sets: 4, rest_sec: 90 }],
    equipment_variant: "gym", difficulty_tier: 2, session_types: ["station_work", "strength"], tags: ["grip"] },
  { id: "st_lunges", block_type: "main", station: "sandbag_lunges",
    content: [{ exercise: "Sandbag walking lunges", distance_m: 50, load_by_division: { open: "20 kg", pro: "30 kg" }, sets: 4, rest_sec: 90 }],
    equipment_variant: "gym", difficulty_tier: 2, session_types: ["station_work", "strength"], tags: ["legs"] },
  { id: "st_wallballs", block_type: "main", station: "wall_balls",
    content: [{ exercise: "Wall balls (unbroken sets)", reps: 25, load_by_division: { open: "6 kg / 3.0 m", pro: "9 kg / 3.0 m" }, sets: 4, rest_sec: 75 }],
    equipment_variant: "gym", difficulty_tier: 1, session_types: ["station_work"], tags: ["wallball"] },

  { id: "str_lower_squat", block_type: "main", station: "general",
    content: [{ exercise: "Back squat", sets: 4, reps: 6, load_by_division: { open: "70% 1RM", pro: "78% 1RM" }, rest_sec: 150 }, { exercise: "Romanian deadlift", sets: 3, reps: 8, rest_sec: 120 }],
    equipment_variant: "gym", difficulty_tier: 2, session_types: ["strength"], tags: ["lower"] },
  { id: "str_push_pull", block_type: "main", station: "general",
    content: [{ exercise: "Push press", sets: 4, reps: 6, rest_sec: 120 }, { exercise: "Pull-ups", sets: 4, reps: 8, rest_sec: 90 }],
    equipment_variant: "gym", difficulty_tier: 2, session_types: ["strength"], tags: ["upper"] },

  { id: "sim_full_hyrox", block_type: "main", station: "general",
    content: [{ exercise: "Full Hyrox simulation: 8x(1000 m run + station)", distance_m: 8000, sets: 1, load_by_division: { open: "all stations @ open", pro: "all stations @ pro" } }],
    equipment_variant: "gym", difficulty_tier: 3, session_types: ["full_sim", "benchmark"], tags: ["simulation"] },
  { id: "sim_half_hyrox", block_type: "main", station: "general",
    content: [{ exercise: "4 rounds: 1000 m run + one station", distance_m: 1000, sets: 4, load_by_division: { open: "open weights", pro: "pro weights" } }],
    equipment_variant: "gym", difficulty_tier: 2, session_types: ["full_sim"], tags: ["simulation"] },

  { id: "mob_lower", block_type: "mobility", station: "general",
    content: [{ exercise: "Couch stretch", reps: 60, sets: 2 }, { exercise: "90/90 hip switches", reps: 10, sets: 2 }],
    equipment_variant: "gym", difficulty_tier: 1, session_types: ["mobility", "strength", "station_work", "compromised_run", "run_intervals", "full_sim"], tags: ["mobility"] },
  { id: "mob_full", block_type: "mobility", station: "general",
    content: [{ exercise: "Thoracic openers", reps: 10, sets: 2 }, { exercise: "Pigeon stretch", reps: 45, sets: 2 }],
    equipment_variant: "gym", difficulty_tier: 1, session_types: ["mobility"], tags: ["mobility"] },
];
