-- ============================================================================
-- Compromised running: 60 sessions, five levels x four phases x three.
--
-- GENERATED from src/lib/engine/compromisedSessions.ts — do not edit by hand.
--   WRITE_SEED=1 npx vitest run compromisedSeed
--
-- The ids are pinned in the catalogue, because the engine names them while
-- building a plan: session_blocks.block_id points straight at these rows.
-- ============================================================================

insert into workout_blocks (id, slug, block_type, station, content, equipment_variant, difficulty_tier, session_types, tags) values
('9f3f6a03-0910-50fa-9426-471bce36f344', 'cr_b1_squat_sandwich', 'main', null,
 '[{"exercise":"3 rounds — 2 min between rounds","rest_sec":120},{"exercise":"Zone 2 run","distance_m":400,"is_run":true},{"exercise":"Goblet squats, light","reps":15},{"exercise":"Zone 2 run","distance_m":400,"is_run":true}]'::jsonb,
 'gym', 1, '{compromised_run}', '{compromised,beginner,base}'),
('b6c3d7c1-839e-542f-9764-1c11fe73c6c1', 'cr_b1_ski_to_run', 'main', 'ski_erg',
 '[{"exercise":"4 rounds"},{"exercise":"SkiErg, aerobic — steady, not a sprint","distance_m":250},{"exercise":"Zone 2 run, straight off the erg","distance_m":500,"is_run":true}]'::jsonb,
 'gym', 1, '{compromised_run}', '{compromised,beginner,base,ski_erg}'),
('b08d6e5a-c82e-51ad-bcd8-2cf993da64d1', 'cr_b1_light_sled', 'main', 'sled_push',
 '[{"exercise":"3 rounds"},{"exercise":"Sled push, light","distance_m":20,"load_by_division":{"open":"50 kg","pro":"75 kg"}},{"exercise":"Easy jog — let the legs come back","distance_m":600,"is_run":true}]'::jsonb,
 'gym', 1, '{compromised_run}', '{compromised,beginner,base,sled_push}'),
('2fc1f3aa-ae02-5b1c-924b-f019459ea528', 'cr_b2_deadlift_burpee', 'main', null,
 '[{"exercise":"4 rounds — 2 min between rounds","rest_sec":90},{"exercise":"Run, Zone 3-4","distance_m":500,"is_run":true},{"exercise":"Kettlebell deadlifts","reps":12,"load_by_division":{"open":"24 kg","pro":"32 kg"}},{"exercise":"Burpees","reps":10}]'::jsonb,
 'gym', 1, '{compromised_run}', '{compromised,beginner,build}'),
('2fd63911-d5bd-5ba1-98d8-2a3bf9680627', 'cr_b2_lunge_to_pace', 'main', 'sandbag_lunges',
 '[{"exercise":"3 rounds — 2 min between rounds","rest_sec":120},{"exercise":"Sandbag lunges, light","distance_m":40,"load_by_division":{"open":"10 kg","pro":"20 kg"}},{"exercise":"Run at race pace, immediately","distance_m":800,"is_run":true}]'::jsonb,
 'gym', 1, '{compromised_run}', '{compromised,beginner,build,sandbag_lunges}'),
('e7e90191-e94e-5484-b9b8-cb1626c245d6', 'cr_b2_row_lunge_run', 'main', 'row',
 '[{"exercise":"4 rounds"},{"exercise":"Row","distance_m":250},{"exercise":"Walking lunges","distance_m":20},{"exercise":"Run","distance_m":500,"is_run":true}]'::jsonb,
 'gym', 1, '{compromised_run}', '{compromised,beginner,build,row}'),
('2fddd0ea-787c-5939-9e54-83e6a9b2d10b', 'cr_b3_mini_sim', 'main', 'wall_balls',
 '[{"exercise":"2 rounds"},{"exercise":"Run at race pace","distance_m":1000,"is_run":true},{"exercise":"SkiErg","distance_m":500},{"exercise":"Run at race pace","distance_m":1000,"is_run":true},{"exercise":"Wall balls","reps":20,"load_by_division":{"open":"6 kg","pro":"9 kg"}}]'::jsonb,
 'gym', 1, '{compromised_run}', '{compromised,beginner,peak,wall_balls}'),
('c92797c9-eaff-5c11-bb58-947dc99ddd0b', 'cr_b3_carry_jump_run', 'main', 'burpee_broad_jump',
 '[{"exercise":"3 rounds"},{"exercise":"Farmers carry","distance_m":50,"load_by_division":{"open":"2×16 kg","pro":"2×24 kg"}},{"exercise":"Burpee broad jumps","reps":15},{"exercise":"Run at race pace, no walk-in","distance_m":1000,"is_run":true}]'::jsonb,
 'gym', 1, '{compromised_run}', '{compromised,beginner,peak,burpee_broad_jump}'),
('34f64495-a5bc-5902-aa46-2df26494ec9a', 'cr_b3_half_sim', 'main', null,
 '[{"exercise":"Four runs, each broken by the next station in race order"},{"exercise":"Run 1 → SkiErg 1000 m","distance_m":1000,"is_run":true},{"exercise":"Run 2 → Sled push 50 m","distance_m":1000,"is_run":true},{"exercise":"Run 3 → Sled pull 50 m","distance_m":1000,"is_run":true},{"exercise":"Run 4 → Burpee broad jumps 80 m","distance_m":1000,"is_run":true}]'::jsonb,
 'gym', 1, '{compromised_run}', '{compromised,beginner,peak}'),
('e0a4ba47-01aa-5657-a18c-ba4435bbb990', 'cr_b4_short_sharp', 'main', 'wall_balls',
 '[{"exercise":"2 rounds"},{"exercise":"Run at race pace","distance_m":400,"is_run":true},{"exercise":"Wall balls","reps":10,"load_by_division":{"open":"6 kg","pro":"9 kg"}},{"exercise":"Run at easy","distance_m":400,"is_run":true}]'::jsonb,
 'gym', 1, '{compromised_run}', '{compromised,beginner,taper,wall_balls}'),
('caf7ab13-a6e1-509e-a14f-7231511edc85', 'cr_b4_transition_drill', 'main', 'ski_erg',
 '[{"exercise":"3 rounds"},{"exercise":"SkiErg","distance_m":200},{"exercise":"Run at race pace — focus on how fast you get moving","distance_m":500,"is_run":true}]'::jsonb,
 'gym', 1, '{compromised_run}', '{compromised,beginner,taper,ski_erg}'),
('e73ee23e-b18b-5322-ad29-32242cc85e77', 'cr_b4_single_rehearsal', 'main', 'sled_push',
 '[{"exercise":"Run at race pace","distance_m":1000,"is_run":true},{"exercise":"Sled push, light","distance_m":20,"load_by_division":{"open":"50 kg","pro":"75 kg"}},{"exercise":"Cool-down run","distance_m":500,"is_run":true}]'::jsonb,
 'gym', 1, '{compromised_run}', '{compromised,beginner,taper,sled_push}'),
('bf4524d0-9fec-5afb-94ba-b4648529bebd', 'cr_i1_squat_row', 'main', 'row',
 '[{"exercise":"4 rounds"},{"exercise":"Zone 2 run","distance_m":800,"is_run":true},{"exercise":"Air squats","reps":20},{"exercise":"Row, aerobic","distance_m":200}]'::jsonb,
 'gym', 1, '{compromised_run}', '{compromised,intermediate,base,row}'),
('ea04c866-a724-5818-9df3-63ac7d353fdc', 'cr_i1_ski_sled_run', 'main', 'sled_push',
 '[{"exercise":"3 rounds"},{"exercise":"SkiErg","distance_m":500},{"exercise":"Sled push at 60% of race weight","distance_m":30,"load_by_division":{"open":"90 kg","pro":"120 kg"}},{"exercise":"Zone 2 run","distance_m":800,"is_run":true}]'::jsonb,
 'gym', 1, '{compromised_run}', '{compromised,intermediate,base,sled_push}'),
('24123a24-d994-5ce1-a5ef-89e9db5dcbcd', 'cr_i1_carry_kilometre', 'main', 'farmers_carry',
 '[{"exercise":"4 rounds"},{"exercise":"Run at zone 2 to low Zone 3","distance_m":1000,"is_run":true},{"exercise":"Farmers walk, moderate","distance_m":40,"load_by_division":{"open":"2×20 kg","pro":"2×28 kg"}}]'::jsonb,
 'gym', 1, '{compromised_run}', '{compromised,intermediate,base,farmers_carry}'),
('7a3bba7a-941b-5e7d-b258-83f13328f509', 'cr_i2_sled_threshold', 'main', 'sled_push',
 '[{"exercise":"4 rounds"},{"exercise":"Sled push at race weight","distance_m":30,"load_by_division":{"open":"152 kg","pro":"202 kg"}},{"exercise":"Run at threshold, Zone 4 — straight off the sled","distance_m":1000,"is_run":true}]'::jsonb,
 'gym', 1, '{compromised_run}', '{compromised,intermediate,build,sled_push}'),
('b7e82c71-83d7-54c1-b36d-22c3ca50a3c2', 'cr_i2_row_bbj_5k', 'main', 'burpee_broad_jump',
 '[{"exercise":"3 rounds — 2 min between rounds","rest_sec":90},{"exercise":"Row","distance_m":500},{"exercise":"Burpee broad jumps","reps":20},{"exercise":"Run at 5k pace","distance_m":800,"is_run":true}]'::jsonb,
 'gym', 1, '{compromised_run}', '{compromised,intermediate,build,burpee_broad_jump}'),
('2b7257c5-a6de-5e9d-a79d-00b59d23a8b0', 'cr_i2_lunge_race_pace', 'main', 'sandbag_lunges',
 '[{"exercise":"4 rounds"},{"exercise":"Sandbag lunges at race weight","distance_m":50,"load_by_division":{"open":"20 kg","pro":"30 kg"}},{"exercise":"Run at race pace","distance_m":1000,"is_run":true}]'::jsonb,
 'gym', 1, '{compromised_run}', '{compromised,intermediate,build,sandbag_lunges}'),
('f91b83a1-cdfd-5d4d-bcb4-9382f24ae499', 'cr_i3_sled_sandwich', 'main', 'wall_balls',
 '[{"exercise":"3 rounds"},{"exercise":"Run at race pace","distance_m":1000,"is_run":true},{"exercise":"Sled push","distance_m":50,"load_by_division":{"open":"152 kg","pro":"202 kg"}},{"exercise":"Run at race pace","distance_m":1000,"is_run":true},{"exercise":"Wall balls","reps":25,"load_by_division":{"open":"6 kg","pro":"9 kg"}}]'::jsonb,
 'gym', 1, '{compromised_run}', '{compromised,intermediate,peak,wall_balls}'),
('35031523-055a-50f0-b078-e1632cbfd74d', 'cr_i3_ski_carry_chain', 'main', 'farmers_carry',
 '[{"exercise":"4 rounds"},{"exercise":"Run at race pace","distance_m":1000,"is_run":true},{"exercise":"SkiErg","distance_m":500},{"exercise":"Farmers carry","distance_m":100,"load_by_division":{"open":"2×24 kg","pro":"2×32 kg"}}]'::jsonb,
 'gym', 1, '{compromised_run}', '{compromised,intermediate,peak,farmers_carry}'),
('710d912c-2a16-5bb0-866d-defbefc5af46', 'cr_i3_brick_density', 'main', 'burpee_broad_jump',
 '[{"exercise":"5 rounds"},{"exercise":"Run at above race pace","distance_m":600,"is_run":true},{"exercise":"Burpee broad jumps","reps":15},{"exercise":"Wall balls","reps":15,"load_by_division":{"open":"6 kg","pro":"9 kg"}}]'::jsonb,
 'gym', 1, '{compromised_run}', '{compromised,intermediate,peak,burpee_broad_jump}'),
('073d2d29-9596-50ba-93fe-0ef81ec70e6e', 'cr_i4_row_sandwich', 'main', 'row',
 '[{"exercise":"3 rounds"},{"exercise":"Run at race pace","distance_m":500,"is_run":true},{"exercise":"Row","distance_m":250},{"exercise":"Run at zone 2","distance_m":500,"is_run":true}]'::jsonb,
 'gym', 1, '{compromised_run}', '{compromised,intermediate,taper,row}'),
('0571705b-3b10-5cb0-9981-14aa87755545', 'cr_i4_sharpening_sled', 'main', 'sled_push',
 '[{"exercise":"2 rounds"},{"exercise":"Run at race pace","distance_m":1000,"is_run":true},{"exercise":"Sled push — sharpening, never to failure","distance_m":20,"load_by_division":{"open":"152 kg","pro":"202 kg"}}]'::jsonb,
 'gym', 1, '{compromised_run}', '{compromised,intermediate,taper,sled_push}'),
('05ef976e-b100-5209-95ef-3f22e8fb74d5', 'cr_i4_over_pace_touch', 'main', 'wall_balls',
 '[{"exercise":"Three efforts, full recovery between"},{"exercise":"Run at above race pace","distance_m":400,"is_run":true},{"exercise":"Wall balls between efforts","reps":10,"load_by_division":{"open":"6 kg","pro":"9 kg"}}]'::jsonb,
 'gym', 1, '{compromised_run}', '{compromised,intermediate,taper,wall_balls}'),
('9324bc34-4403-5811-80b1-8c184d5d4b36', 'cr_a1_ski_carry_volume', 'main', 'farmers_carry',
 '[{"exercise":"5 rounds"},{"exercise":"Zone 2 run","distance_m":1000,"is_run":true},{"exercise":"SkiErg, aerobic","distance_m":500},{"exercise":"Heavy kettlebell carry","distance_m":40,"load_by_division":{"open":"2×28 kg","pro":"2×32 kg"}}]'::jsonb,
 'gym', 2, '{compromised_run}', '{compromised,advanced,base,farmers_carry}'),
('1df8d898-bfe3-51b5-b215-1f0b6bcd497a', 'cr_a1_double_sled', 'main', 'sled_pull',
 '[{"exercise":"4 rounds"},{"exercise":"Run","distance_m":800,"is_run":true},{"exercise":"Heavy sled push","distance_m":30,"load_by_division":{"open":"175 kg","pro":"225 kg"}},{"exercise":"Heavy sled pull","distance_m":30,"load_by_division":{"open":"125 kg","pro":"175 kg"}}]'::jsonb,
 'gym', 2, '{compromised_run}', '{compromised,advanced,base,sled_pull}'),
('cc041fcf-9847-5db8-bca1-5341fa91d00b', 'cr_a1_long_z2_brick', 'main', 'row',
 '[{"exercise":"3 rounds"},{"exercise":"Zone 2 run","distance_m":1500,"is_run":true},{"exercise":"Goblet squats","reps":30,"load_by_division":{"open":"24 kg","pro":"32 kg"}},{"exercise":"Row","distance_m":500}]'::jsonb,
 'gym', 2, '{compromised_run}', '{compromised,advanced,base,row}'),
('1436392a-8bc4-5c62-a061-14c488810303', 'cr_a2_sled_pace_discipline', 'main', 'sled_push',
 '[{"exercise":"4 rounds"},{"exercise":"Sled push at competition weight","distance_m":50,"load_by_division":{"open":"152 kg","pro":"202 kg"}},{"exercise":"Run at threshold — hold 4:45-5:00 min/km, no faster off the sled","distance_m":1000,"is_run":true}]'::jsonb,
 'gym', 2, '{compromised_run}', '{compromised,advanced,build,sled_push}'),
('cc8b0e21-2fdf-554d-9b68-e9e3a324e212', 'cr_a2_row_lunge_race', 'main', 'sandbag_lunges',
 '[{"exercise":"3 rounds — 2 min between rounds","rest_sec":120},{"exercise":"Row at race pace","distance_m":500},{"exercise":"Sandbag lunges","distance_m":60,"load_by_division":{"open":"20 kg","pro":"30 kg"}},{"exercise":"Run at race pace","distance_m":1000,"is_run":true}]'::jsonb,
 'gym', 2, '{compromised_run}', '{compromised,advanced,build,sandbag_lunges}'),
('66fe6ee5-a914-51da-b625-2d87532749e5', 'cr_a2_jumps_walls_5k', 'main', 'burpee_broad_jump',
 '[{"exercise":"4 rounds"},{"exercise":"Burpee broad jumps","reps":20},{"exercise":"Wall balls","reps":25,"load_by_division":{"open":"6 kg","pro":"9 kg"}},{"exercise":"Run at 5k pace","distance_m":1000,"is_run":true}]'::jsonb,
 'gym', 2, '{compromised_run}', '{compromised,advanced,build,burpee_broad_jump}'),
('20cc220c-3d30-5091-8480-2736e5d84fe2', 'cr_a3_split_consistency', 'main', 'sled_pull',
 '[{"exercise":"4 rounds"},{"exercise":"Run at race pace — note the split","distance_m":1000,"is_run":true},{"exercise":"Sled push","distance_m":50,"load_by_division":{"open":"152 kg","pro":"202 kg"}},{"exercise":"Run at race pace — within 5 s of the first","distance_m":1000,"is_run":true},{"exercise":"Sled pull","distance_m":50,"load_by_division":{"open":"103 kg","pro":"153 kg"}}]'::jsonb,
 'gym', 2, '{compromised_run}', '{compromised,advanced,peak,sled_pull}'),
('3da94aa0-999c-5428-8be3-8658004e0149', 'cr_a3_race_intensity_chain', 'main', 'wall_balls',
 '[{"exercise":"3 rounds"},{"exercise":"Run at race pace","distance_m":1000,"is_run":true},{"exercise":"SkiErg","distance_m":500},{"exercise":"Farmers carry","distance_m":100,"load_by_division":{"open":"2×24 kg","pro":"2×32 kg"}},{"exercise":"Wall balls at race intensity","reps":50,"load_by_division":{"open":"6 kg","pro":"9 kg"}}]'::jsonb,
 'gym', 2, '{compromised_run}', '{compromised,advanced,peak,wall_balls}'),
('c6810fd0-4c00-5003-9db1-ecdcb3a95993', 'cr_a3_pacing_stress', 'main', 'sandbag_lunges',
 '[{"exercise":"Six efforts, alternating the station between them"},{"exercise":"Run 5-10 s/km faster than race pace","distance_m":800,"is_run":true},{"exercise":"Lunges (odd rounds)","distance_m":40,"load_by_division":{"open":"20 kg","pro":"30 kg"}},{"exercise":"Burpee broad jumps (even rounds)","reps":20}]'::jsonb,
 'gym', 2, '{compromised_run}', '{compromised,advanced,peak,sandbag_lunges}'),
('8f68273c-af1c-5eb8-976a-63cc345c2aa3', 'cr_a4_ski_sandwich', 'main', 'ski_erg',
 '[{"exercise":"3 rounds"},{"exercise":"Run at race pace","distance_m":600,"is_run":true},{"exercise":"SkiErg","distance_m":250},{"exercise":"Run at zone 2","distance_m":400,"is_run":true}]'::jsonb,
 'gym', 2, '{compromised_run}', '{compromised,advanced,taper,ski_erg}'),
('15a76eec-83e8-586a-aefb-af26e45db07c', 'cr_a4_kilometre_touch', 'main', 'sled_push',
 '[{"exercise":"2 rounds"},{"exercise":"Run at race pace","distance_m":1000,"is_run":true},{"exercise":"Sled push, short","distance_m":25,"load_by_division":{"open":"152 kg","pro":"202 kg"}},{"exercise":"Wall balls","reps":15,"load_by_division":{"open":"6 kg","pro":"9 kg"}}]'::jsonb,
 'gym', 2, '{compromised_run}', '{compromised,advanced,taper,sled_push}'),
('c18b695b-dc1d-56c6-a217-51413c89fb81', 'cr_a4_roxzone_drills', 'main', null,
 '[{"exercise":"Four accelerations with a full transition rehearsal after each"},{"exercise":"Run: accelerate to race pace and beyond","distance_m":300,"is_run":true},{"exercise":"Transition drill — into and out of the station area, fast"}]'::jsonb,
 'gym', 2, '{compromised_run}', '{compromised,advanced,taper}'),
('cc1394cb-130c-5627-ae61-2bcd46264d16', 'cr_e1_ski_drag_volume', 'main', 'ski_erg',
 '[{"exercise":"5 rounds"},{"exercise":"Zone 2 run","distance_m":1200,"is_run":true},{"exercise":"SkiErg, aerobic","distance_m":500},{"exercise":"Sled drag","distance_m":50,"load_by_division":{"open":"103 kg","pro":"153 kg"}}]'::jsonb,
 'gym', 3, '{compromised_run}', '{compromised,elite,base,ski_erg}'),
('5894ccfe-fe02-5bd5-855f-e56865dcc9cc', 'cr_e1_heavy_double_sled', 'main', 'sled_push',
 '[{"exercise":"4 rounds"},{"exercise":"Run","distance_m":1000,"is_run":true},{"exercise":"Heavy sled push","distance_m":40,"load_by_division":{"open":"120+ kg","pro":"180+ kg"}},{"exercise":"Heavy sled pull","distance_m":40,"load_by_division":{"open":"120 kg","pro":"160 kg"}}]'::jsonb,
 'gym', 3, '{compromised_run}', '{compromised,elite,base,sled_push}'),
('48f71c48-800a-5eb2-825d-4b4621dbe421', 'cr_e1_long_aerobic_chain', 'main', 'farmers_carry',
 '[{"exercise":"3 rounds"},{"exercise":"Zone 2 run","distance_m":2000,"is_run":true},{"exercise":"Row","distance_m":1000},{"exercise":"Farmers carry","distance_m":100,"load_by_division":{"open":"2×32 kg","pro":"2×32 kg"}}]'::jsonb,
 'gym', 3, '{compromised_run}', '{compromised,elite,base,farmers_carry}'),
('02077719-5b5b-56cf-bf4f-aad5b8c9828d', 'cr_e2_lactate_accumulation', 'main', 'sled_push',
 '[{"exercise":"4 rounds"},{"exercise":"Sled push, maximum pressure","distance_m":50,"load_by_division":{"open":"152 kg","pro":"202 kg"}},{"exercise":"Run at 4:15-4:25 min/km — no transition, straight into it","distance_m":1000,"is_run":true}]'::jsonb,
 'gym', 3, '{compromised_run}', '{compromised,elite,build,sled_push}'),
('28b0603c-8908-5890-830e-b6c899963e55', 'cr_e2_row_bbj_subthreshold', 'main', 'burpee_broad_jump',
 '[{"exercise":"4 rounds — 3 min between rounds","rest_sec":180},{"exercise":"Row at race pace","distance_m":500},{"exercise":"Burpee broad jumps","reps":25},{"exercise":"Run at sub-threshold","distance_m":1000,"is_run":true}]'::jsonb,
 'gym', 3, '{compromised_run}', '{compromised,elite,build,burpee_broad_jump}'),
('dd93d730-85f1-5fbb-b28f-31a08f41f927', 'cr_e2_lunge_split_drift', 'main', 'sandbag_lunges',
 '[{"exercise":"4 rounds"},{"exercise":"Sandbag lunges","distance_m":80,"load_by_division":{"open":"20 kg","pro":"30 kg"}},{"exercise":"Run — splits may drift by 5 s across the session, no more","distance_m":1000,"is_run":true}]'::jsonb,
 'gym', 3, '{compromised_run}', '{compromised,elite,build,sandbag_lunges}'),
('0b69458f-1739-5194-a356-baeedae5d51d', 'cr_e3_race_density', 'main', 'sled_pull',
 '[{"exercise":"3 rounds"},{"exercise":"Row","distance_m":500},{"exercise":"Run at race pace","distance_m":1000,"is_run":true},{"exercise":"Sled push","distance_m":50,"load_by_division":{"open":"152 kg","pro":"202 kg"}},{"exercise":"Run at race pace","distance_m":1000,"is_run":true},{"exercise":"Sled pull","distance_m":50,"load_by_division":{"open":"103 kg","pro":"153 kg"}},{"exercise":"Run at race pace","distance_m":1000,"is_run":true},{"exercise":"Burpee broad jumps","reps":25},{"exercise":"Run at race pace","distance_m":1000,"is_run":true}]'::jsonb,
 'gym', 3, '{compromised_run}', '{compromised,elite,peak,sled_pull}'),
('369fe786-8848-5aea-bd6f-4c91db65e918', 'cr_e3_lactate_washout', 'main', 'wall_balls',
 '[{"exercise":"5 rounds — 2 min between rounds","rest_sec":120},{"exercise":"Run at 4:05 min/km","distance_m":1000,"is_run":true},{"exercise":"Wall balls, unbroken","reps":30,"load_by_division":{"open":"6 kg","pro":"9 kg"}}]'::jsonb,
 'gym', 3, '{compromised_run}', '{compromised,elite,peak,wall_balls}'),
('320d444b-a26e-5076-817e-4a0ca1e91eb5', 'cr_e3_high_velocity_brick', 'main', 'farmers_carry',
 '[{"exercise":"Six efforts, the station rotates between them"},{"exercise":"Run at under 3:20","distance_m":800,"is_run":true},{"exercise":"Farmers carry (round 1, 4)","distance_m":200,"load_by_division":{"open":"2×24 kg","pro":"2×32 kg"}},{"exercise":"Lunges (round 2, 5)","distance_m":50,"load_by_division":{"open":"20 kg","pro":"30 kg"}},{"exercise":"SkiErg (round 3, 6)","distance_m":500}]'::jsonb,
 'gym', 3, '{compromised_run}', '{compromised,elite,peak,farmers_carry}'),
('d612d12f-31ab-591e-ad07-2a98e50051fd', 'cr_e4_race_pace_ski', 'main', 'ski_erg',
 '[{"exercise":"3 rounds"},{"exercise":"Run at race pace, 4:15 min/km","distance_m":800,"is_run":true},{"exercise":"SkiErg","distance_m":250},{"exercise":"Wall balls","reps":10,"load_by_division":{"open":"6 kg","pro":"9 kg"}}]'::jsonb,
 'gym', 3, '{compromised_run}', '{compromised,elite,taper,ski_erg}'),
('1d98c844-90c7-519e-a052-cd752a7d5e59', 'cr_e4_neuromuscular_sled', 'main', 'sled_push',
 '[{"exercise":"2 rounds"},{"exercise":"Run at race pace","distance_m":1000,"is_run":true},{"exercise":"Sled push at 80% — activation, not fatigue","distance_m":25,"load_by_division":{"open":"122 kg","pro":"162 kg"}}]'::jsonb,
 'gym', 3, '{compromised_run}', '{compromised,elite,taper,sled_push}'),
('4982d9ca-e7e3-563f-bfc5-290cc62d6dc5', 'cr_e4_explosive_touch', 'main', 'burpee_broad_jump',
 '[{"exercise":"Four efforts, full recovery between"},{"exercise":"Run at race pace","distance_m":400,"is_run":true},{"exercise":"Burpee broad jumps, explosive","reps":5}]'::jsonb,
 'gym', 3, '{compromised_run}', '{compromised,elite,taper,burpee_broad_jump}'),
('d9b88256-114f-53c7-b742-798678464608', 'cr_w1_ski_carry_volume', 'main', 'ski_erg',
 '[{"exercise":"6 rounds"},{"exercise":"Zone 2 run","distance_m":1200,"is_run":true},{"exercise":"SkiErg, aerobic","distance_m":1000},{"exercise":"Heavy carry","distance_m":60,"load_by_division":{"open":"2×32 kg","pro":"2×32 kg"}}]'::jsonb,
 'gym', 3, '{compromised_run}', '{compromised,world_class,base,ski_erg}'),
('a678349f-53cb-5c1c-8094-e30c77a4de95', 'cr_w1_overload_sled', 'main', 'sled_push',
 '[{"exercise":"5 rounds"},{"exercise":"Run at aerobic threshold","distance_m":1000,"is_run":true},{"exercise":"Heavy overload sled push","distance_m":50,"load_by_division":{"open":"150+ kg","pro":"200+ kg"}}]'::jsonb,
 'gym', 3, '{compromised_run}', '{compromised,world_class,base,sled_push}'),
('9b1a6fa2-415c-5236-a524-0130f683cd83', 'cr_w1_lt1_row_squat', 'main', 'row',
 '[{"exercise":"4 rounds"},{"exercise":"Run","distance_m":1500,"is_run":true},{"exercise":"Row at LT1","distance_m":1000},{"exercise":"Back squats, heavy","reps":30}]'::jsonb,
 'gym', 3, '{compromised_run}', '{compromised,world_class,base,row}'),
('625db2ec-b925-5784-84d9-e8600f72408d', 'cr_w2_glycolytic_stress', 'main', 'sled_push',
 '[{"exercise":"5 rounds"},{"exercise":"Sled push at Pro weight","distance_m":50,"load_by_division":{"open":"202 kg","pro":"202 kg"}},{"exercise":"Transition — under 5 seconds"},{"exercise":"Run at 3:45-3:55 min/km","distance_m":1000,"is_run":true}]'::jsonb,
 'gym', 3, '{compromised_run}', '{compromised,world_class,build,sled_push}'),
('1420db8a-26a7-5d18-9060-70f2d1bc208f', 'cr_w2_lunge_split_precision', 'main', 'sandbag_lunges',
 '[{"exercise":"4 rounds"},{"exercise":"Sandbag lunges","distance_m":100,"load_by_division":{"open":"30 kg","pro":"30 kg"}},{"exercise":"Run at 3:50 min/km — split variance under 3 s","distance_m":1000,"is_run":true}]'::jsonb,
 'gym', 3, '{compromised_run}', '{compromised,world_class,build,sandbag_lunges}'),
('a8b55089-828a-55d6-b37f-17adac2fc1bb', 'cr_w2_ski_bbj_vo2', 'main', 'burpee_broad_jump',
 '[{"exercise":"5 rounds"},{"exercise":"SkiErg — under 1:40 / 500 m","distance_m":500},{"exercise":"Burpee broad jumps","reps":30},{"exercise":"Run at VO₂max pace","distance_m":1000,"is_run":true}]'::jsonb,
 'gym', 3, '{compromised_run}', '{compromised,world_class,build,burpee_broad_jump}'),
('2c0c9deb-e1b4-5f7e-9b9f-e105b4884f0e', 'cr_w3_roxzone_precision', 'main', null,
 '[{"exercise":"Six efforts, a different station after each — race order, race conditions"},{"exercise":"Run at sub-3:50 min/km","distance_m":1000,"is_run":true},{"exercise":"Station after each run: Ski, Sled Push, Sled Pull, Row, Lunges, Wall Balls"}]'::jsonb,
 'gym', 3, '{compromised_run}', '{compromised,world_class,peak}'),
('dfced421-fb61-5923-a42d-b8387899dda2', 'cr_w3_lactate_buffer', 'main', 'wall_balls',
 '[{"exercise":"4 rounds"},{"exercise":"Run at 3:40 min/km","distance_m":1000,"is_run":true},{"exercise":"Wall balls, unbroken","reps":50,"load_by_division":{"open":"6 kg","pro":"9 kg"}},{"exercise":"Farmers carry","distance_m":100,"load_by_division":{"open":"2×32 kg","pro":"2×32 kg"}}]'::jsonb,
 'gym', 3, '{compromised_run}', '{compromised,world_class,peak,wall_balls}'),
('48a269ed-c932-5a62-98f0-fe89d425b542', 'cr_w3_dynamic_integration', 'main', 'sled_pull',
 '[{"exercise":"Eight efforts, station rotates, rest minimised to zero"},{"exercise":"Run at 3:30 min/km","distance_m":600,"is_run":true},{"exercise":"Sled drag (rounds 1, 4, 7)","distance_m":30,"load_by_division":{"open":"103 kg","pro":"153 kg"}},{"exercise":"Burpee broad jumps (rounds 2, 5, 8)","reps":15},{"exercise":"SkiErg (rounds 3, 6)","distance_m":250}]'::jsonb,
 'gym', 3, '{compromised_run}', '{compromised,world_class,peak,sled_pull}'),
('964c9dbe-dfde-5f13-a898-ec1eeee00bc9', 'cr_w4_cadence_focus', 'main', 'row',
 '[{"exercise":"3 rounds"},{"exercise":"Run at race pace, 3:45 min/km — cadence and breathing","distance_m":600,"is_run":true},{"exercise":"Row","distance_m":250},{"exercise":"Wall balls","reps":10,"load_by_division":{"open":"6 kg","pro":"9 kg"}}]'::jsonb,
 'gym', 3, '{compromised_run}', '{compromised,world_class,taper,row}'),
('893102c6-00e1-55d1-90e1-6cf71d3ff3ec', 'cr_w4_short_sharp_stimuli', 'main', 'sled_push',
 '[{"exercise":"2 rounds"},{"exercise":"Run at race pace","distance_m":800,"is_run":true},{"exercise":"Sled push, short","distance_m":20,"load_by_division":{"open":"202 kg","pro":"202 kg"}},{"exercise":"Carry","distance_m":100,"load_by_division":{"open":"2×32 kg","pro":"2×32 kg"}}]'::jsonb,
 'gym', 3, '{compromised_run}', '{compromised,world_class,taper,sled_push}'),
('5407b926-4932-574f-9288-e8196a3f5791', 'cr_w4_cns_activation', 'main', 'burpee_broad_jump',
 '[{"exercise":"Three efforts, full recovery between"},{"exercise":"Run at competition tempo","distance_m":400,"is_run":true},{"exercise":"Dynamic box or broad jumps","reps":5}]'::jsonb,
 'gym', 3, '{compromised_run}', '{compromised,world_class,taper,burpee_broad_jump}')
on conflict (slug) do update set
  content = excluded.content,
  station = excluded.station,
  difficulty_tier = excluded.difficulty_tier,
  session_types = excluded.session_types,
  tags = excluded.tags;
