-- ============================================================================
-- Isolated station work: 60 sessions, five levels x four phases x three.
--
-- GENERATED from src/lib/engine/stationSessions.ts — do not edit by hand.
--   WRITE_SEED=1 npx vitest run librarySeed
--
-- The ids are pinned in the catalogue, because the engine names them while
-- building a plan: session_blocks.block_id points straight at these rows.
-- ============================================================================

insert into workout_blocks (id, slug, block_type, station, content, equipment_variant, difficulty_tier, session_types, tags) values
('5fa7f714-965e-5c22-bca1-2fe7a0d9143f', 'sw_b1_erg_basics', 'main', 'ski_erg',
 '[{"exercise":"4 rounds"},{"exercise":"SkiErg — hold one pace, do not chase it","distance_m":250,"rest_sec":90},{"exercise":"RowErg — legs, hips, arms, in that order","distance_m":250,"rest_sec":90}]'::jsonb,
 'gym', 1, '{station_work}', '{station,beginner,base,ski_erg}'),
('2ce816c1-0c6e-5726-aeeb-01147740a769', 'sw_b1_sled_mechanics', 'main', 'sled_push',
 '[{"exercise":"4 rounds — 2 min between rounds","rest_sec":120},{"exercise":"Sled push, light — low centre of gravity, small fast steps","distance_m":20,"load_by_division":{"open":"75 kg","pro":"100 kg"}},{"exercise":"Sled pull, hand over hand — stay seated back, do not stand up","distance_m":20,"load_by_division":{"open":"50 kg","pro":"75 kg"}}]'::jsonb,
 'gym', 1, '{station_work}', '{station,beginner,base,sled_push}'),
('ce6bd7f4-5089-5ede-b5fe-865fb600524b', 'sw_b1_squat_carry_base', 'main', 'farmers_carry',
 '[{"exercise":"3 rounds — 90 s between rounds","rest_sec":90},{"exercise":"Goblet squats — full depth, chest up","reps":12},{"exercise":"Farmers carry, light","distance_m":40,"load_by_division":{"open":"2×16 kg","pro":"2×20 kg"}},{"exercise":"Walking lunges, bodyweight","reps":10}]'::jsonb,
 'gym', 1, '{station_work}', '{station,beginner,base,farmers_carry}'),
('85404794-ddef-5e07-9bf0-9b269369bdd8', 'sw_b2_ski_wallball', 'main', 'wall_balls',
 '[{"exercise":"4 rounds — 1 min between rounds","rest_sec":60},{"exercise":"SkiErg","distance_m":500},{"exercise":"Wall balls, light — hip crease below the knee every rep","reps":15,"load_by_division":{"open":"4 kg","pro":"6 kg"}}]'::jsonb,
 'gym', 1, '{station_work}', '{station,beginner,build,wall_balls}'),
('a601a2f0-78fb-5548-a380-8ddd19659ec2', 'sw_b2_emom_stations', 'main', 'sled_push',
 '[{"exercise":"4 rounds"},{"exercise":"Minute 1 — sled push, moderate","distance_m":15,"load_by_division":{"open":"100 kg","pro":"125 kg"}},{"exercise":"Minute 2 — farmers carry","distance_m":30,"load_by_division":{"open":"2×24 kg","pro":"2×32 kg"}},{"exercise":"Minute 3 — burpee broad jumps","reps":8},{"exercise":"Minute 4 — rest","rest_sec":60}]'::jsonb,
 'gym', 1, '{station_work}', '{station,beginner,build,sled_push}'),
('fb6db75c-bf8b-5875-8144-49f825ccae35', 'sw_b2_row_lunge_ball', 'main', 'row',
 '[{"exercise":"3 rounds — 2 min between rounds","rest_sec":120},{"exercise":"RowErg","distance_m":500},{"exercise":"Walking lunges, light","distance_m":20},{"exercise":"Wall balls","reps":12,"load_by_division":{"open":"4 kg","pro":"6 kg"}}]'::jsonb,
 'gym', 1, '{station_work}', '{station,beginner,build,row}'),
('e1057bc1-5369-5927-805d-f18cc2807793', 'sw_b3_circuit_a', 'main', 'sled_push',
 '[{"exercise":"3 rounds — 2 min between rounds","rest_sec":120},{"exercise":"SkiErg","distance_m":500},{"exercise":"Sled push at race weight","distance_m":25,"load_by_division":{"open":"152 kg","pro":"202 kg"}},{"exercise":"Sled pull at race weight","distance_m":25,"load_by_division":{"open":"103 kg","pro":"153 kg"}}]'::jsonb,
 'gym', 1, '{station_work}', '{station,beginner,peak,sled_push}'),
('cdf74a54-6c23-530f-bb45-baf554289d6d', 'sw_b3_circuit_b', 'main', 'wall_balls',
 '[{"exercise":"3 rounds — 2 min between rounds","rest_sec":120},{"exercise":"RowErg","distance_m":500},{"exercise":"Farmers carry","distance_m":50,"load_by_division":{"open":"2×24 kg","pro":"2×32 kg"}},{"exercise":"Burpee broad jumps","reps":15},{"exercise":"Wall balls","reps":25,"load_by_division":{"open":"6 kg","pro":"9 kg"}}]'::jsonb,
 'gym', 1, '{station_work}', '{station,beginner,peak,wall_balls}'),
('37c720b8-7516-52f7-9f44-d88df27740b4', 'sw_b3_half_sim', 'main', 'burpee_broad_jump',
 '[{"exercise":"SkiErg","distance_m":1000,"rest_sec":120},{"exercise":"Sled push at race weight","distance_m":50,"load_by_division":{"open":"152 kg","pro":"202 kg"},"rest_sec":120},{"exercise":"Sled pull at race weight","distance_m":50,"load_by_division":{"open":"103 kg","pro":"153 kg"},"rest_sec":120},{"exercise":"Burpee broad jumps","distance_m":80}]'::jsonb,
 'gym', 1, '{station_work}', '{station,beginner,peak,burpee_broad_jump}'),
('9f6fa682-f7a8-5694-ac8c-461b55bb1b6a', 'sw_b4_race_pace_touch', 'main', 'ski_erg',
 '[{"exercise":"2 rounds — 90 s between rounds","rest_sec":90},{"exercise":"SkiErg at race pace","distance_m":250},{"exercise":"Wall balls","reps":10,"load_by_division":{"open":"6 kg","pro":"9 kg"}}]'::jsonb,
 'gym', 1, '{station_work}', '{station,beginner,taper,ski_erg}'),
('838306bc-6d4f-5837-8760-a4e00ec28d01', 'sw_b4_sled_primer', 'main', 'sled_push',
 '[{"exercise":"3 rounds"},{"exercise":"Sled push at race weight","distance_m":12.5,"load_by_division":{"open":"152 kg","pro":"202 kg"}},{"exercise":"Farmers carry","distance_m":25,"load_by_division":{"open":"2×24 kg","pro":"2×32 kg"}},{"exercise":"Full recovery before the next set","rest_sec":180}]'::jsonb,
 'gym', 1, '{station_work}', '{station,beginner,taper,sled_push}'),
('1c068c95-b901-5924-9f61-9decc3fb17fa', 'sw_b4_row_jumps', 'main', 'burpee_broad_jump',
 '[{"exercise":"2 rounds"},{"exercise":"RowErg, controlled","distance_m":250},{"exercise":"Burpee broad jumps — clean chest-to-floor, full jump","reps":5}]'::jsonb,
 'gym', 1, '{station_work}', '{station,beginner,taper,burpee_broad_jump}'),
('dac5d3ea-fa22-554a-9a0f-c6c0d63ee4d5', 'sw_i1_erg_aerobic_power', 'main', 'row',
 '[{"exercise":"5 rounds — 90 s between rounds","rest_sec":90},{"exercise":"500 m at threshold pace — alternate RowErg and SkiErg each round","distance_m":500}]'::jsonb,
 'gym', 1, '{station_work}', '{station,intermediate,base,row}'),
('2a07f711-5eb7-56d7-8c33-b477148880ff', 'sw_i1_heavy_sled_foundations', 'main', 'sled_push',
 '[{"exercise":"5 rounds — 2 min between rounds","rest_sec":120},{"exercise":"Sled push, +20% over race weight","distance_m":25,"load_by_division":{"open":"182 kg","pro":"242 kg"}},{"exercise":"Sled pull, heavy","distance_m":25,"load_by_division":{"open":"123 kg","pro":"183 kg"}}]'::jsonb,
 'gym', 1, '{station_work}', '{station,intermediate,base,sled_push}'),
('bbac570a-e0a1-529a-8eed-b58da57e9c4e', 'sw_i1_volume_accumulation', 'main', 'sandbag_lunges',
 '[{"exercise":"4 rounds — 90 s between rounds","rest_sec":90},{"exercise":"Sandbag lunges","distance_m":40,"load_by_division":{"open":"10 kg","pro":"20 kg"}},{"exercise":"Farmers carry","distance_m":60,"load_by_division":{"open":"2×24 kg","pro":"2×32 kg"}},{"exercise":"Burpee broad jumps","reps":15}]'::jsonb,
 'gym', 1, '{station_work}', '{station,intermediate,base,sandbag_lunges}'),
('64eb2196-979a-5bab-9ea4-b4429c2e8dc5', 'sw_i2_ski_push_wallball', 'main', 'wall_balls',
 '[{"exercise":"4 rounds — 90 s between rounds","rest_sec":90},{"exercise":"SkiErg under 2:00 / 500 m","distance_m":500},{"exercise":"Sled push at race weight","distance_m":25,"load_by_division":{"open":"152 kg","pro":"202 kg"}},{"exercise":"Wall balls, unbroken","reps":20,"load_by_division":{"open":"6 kg","pro":"9 kg"}}]'::jsonb,
 'gym', 1, '{station_work}', '{station,intermediate,build,wall_balls}'),
('8e5afd3b-61a8-5e94-8fd6-3f5391ad0117', 'sw_i2_row_pull_carry', 'main', 'sled_pull',
 '[{"exercise":"4 rounds — 90 s between rounds","rest_sec":90},{"exercise":"RowErg","distance_m":500},{"exercise":"Sled pull at race weight","distance_m":50,"load_by_division":{"open":"103 kg","pro":"153 kg"}},{"exercise":"Farmers carry","distance_m":50,"load_by_division":{"open":"2×24 kg","pro":"2×32 kg"}}]'::jsonb,
 'gym', 1, '{station_work}', '{station,intermediate,build,sled_pull}'),
('abb01c23-f88f-5048-9853-66d80bbf369e', 'sw_i2_lactate_tolerance', 'main', 'burpee_broad_jump',
 '[{"exercise":"3 rounds — 2 min between rounds","rest_sec":120},{"exercise":"Burpee broad jumps","reps":30},{"exercise":"Wall balls at open weight","reps":30,"load_by_division":{"open":"6 kg","pro":"6 kg"}}]'::jsonb,
 'gym', 1, '{station_work}', '{station,intermediate,build,burpee_broad_jump}'),
('2f7ecc5a-d586-5291-97e1-0c86a33cfaec', 'sw_i3_upper_pull_chain', 'main', 'sled_pull',
 '[{"exercise":"3 rounds — 150 s between rounds","rest_sec":150},{"exercise":"SkiErg","distance_m":1000},{"exercise":"Sled pull at race weight","distance_m":50,"load_by_division":{"open":"103 kg","pro":"153 kg"}},{"exercise":"RowErg","distance_m":1000}]'::jsonb,
 'gym', 1, '{station_work}', '{station,intermediate,peak,sled_pull}'),
('7c11346b-d362-5f7a-af2c-d2fd8cc88e74', 'sw_i3_lower_push_chain', 'main', 'sled_push',
 '[{"exercise":"3 rounds — 150 s between rounds","rest_sec":150},{"exercise":"Sled push at race weight","distance_m":50,"load_by_division":{"open":"152 kg","pro":"202 kg"}},{"exercise":"Sandbag lunges","distance_m":50,"load_by_division":{"open":"20 kg","pro":"30 kg"}},{"exercise":"Wall balls","reps":50,"load_by_division":{"open":"6 kg","pro":"9 kg"}}]'::jsonb,
 'gym', 1, '{station_work}', '{station,intermediate,peak,sled_push}'),
('d692e099-2a13-53d1-b0cf-37bf9a6529aa', 'sw_i3_station_sim', 'main', null,
 '[{"exercise":"SkiErg","distance_m":500,"rest_sec":60},{"exercise":"Sled push at race weight","distance_m":25,"load_by_division":{"open":"152 kg","pro":"202 kg"},"rest_sec":60},{"exercise":"Sled pull at race weight","distance_m":25,"load_by_division":{"open":"103 kg","pro":"153 kg"},"rest_sec":60},{"exercise":"Burpee broad jumps","distance_m":40,"rest_sec":60},{"exercise":"RowErg","distance_m":500,"rest_sec":60},{"exercise":"Farmers carry","distance_m":100,"load_by_division":{"open":"2×24 kg","pro":"2×32 kg"},"rest_sec":60},{"exercise":"Sandbag lunges","distance_m":50,"load_by_division":{"open":"20 kg","pro":"30 kg"},"rest_sec":60},{"exercise":"Wall balls","reps":50,"load_by_division":{"open":"6 kg","pro":"9 kg"}}]'::jsonb,
 'gym', 1, '{station_work}', '{station,intermediate,peak}'),
('d4c4c3d5-f6ea-552c-a0eb-8865c4ca5208', 'sw_i4_ski_explosive_push', 'main', 'ski_erg',
 '[{"exercise":"3 rounds — 2 min between rounds","rest_sec":120},{"exercise":"SkiErg at race pace","distance_m":250},{"exercise":"Sled push, explosive — accelerate, do not grind","distance_m":10,"load_by_division":{"open":"152 kg","pro":"202 kg"}}]'::jsonb,
 'gym', 1, '{station_work}', '{station,intermediate,taper,ski_erg}'),
('d10405ef-0ee0-52bf-b96a-3cb6d45eb9cf', 'sw_i4_row_unbroken_balls', 'main', 'wall_balls',
 '[{"exercise":"2 rounds"},{"exercise":"RowErg","distance_m":200},{"exercise":"Wall balls, unbroken","reps":15,"load_by_division":{"open":"6 kg","pro":"9 kg"}}]'::jsonb,
 'gym', 1, '{station_work}', '{station,intermediate,taper,wall_balls}'),
('daafa156-c974-5a6a-a7df-832b6af8d7e1', 'sw_i4_carry_jump_touch', 'main', 'farmers_carry',
 '[{"exercise":"3 rounds"},{"exercise":"Farmers carry, brisk","distance_m":20,"load_by_division":{"open":"2×24 kg","pro":"2×32 kg"}},{"exercise":"Burpee broad jumps — maximum distance per jump","reps":4}]'::jsonb,
 'gym', 1, '{station_work}', '{station,intermediate,taper,farmers_carry}'),
('2bda770b-7238-5a08-a150-2dab202c5940', 'sw_a1_erg_threshold', 'main', 'ski_erg',
 '[{"exercise":"6 rounds — 1 min between rounds","rest_sec":60},{"exercise":"SkiErg, sub 1:55 / 500 m","distance_m":500}]'::jsonb,
 'gym', 2, '{station_work}', '{station,advanced,base,ski_erg}'),
('14cbdef0-5dbd-56d7-a1f6-f577bc3c7f1f', 'sw_a1_overload_sled_grip', 'main', 'sled_push',
 '[{"exercise":"5 rounds — 2 min between rounds","rest_sec":120},{"exercise":"Sled push, race weight +30 kg","distance_m":25,"load_by_division":{"open":"182 kg","pro":"232 kg"}},{"exercise":"Sled pull, heavy","distance_m":25,"load_by_division":{"open":"123 kg","pro":"173 kg"}},{"exercise":"Farmers carry, heavy","distance_m":60,"load_by_division":{"open":"2×28 kg","pro":"2×32 kg"}}]'::jsonb,
 'gym', 2, '{station_work}', '{station,advanced,base,sled_push}'),
('b4f8299c-432c-58d1-b807-91d62ada541e', 'sw_a1_metcon_row_jumps', 'main', 'row',
 '[{"exercise":"4 rounds — 2 min between rounds","rest_sec":120},{"exercise":"RowErg","distance_m":500},{"exercise":"Burpee broad jumps — hold the distance per jump","reps":20},{"exercise":"Goblet squats, heavy","reps":20,"load_by_division":{"open":"24 kg","pro":"32 kg"}}]'::jsonb,
 'gym', 2, '{station_work}', '{station,advanced,base,row}'),
('703043ea-96ab-5636-8094-fd68fc631d01', 'sw_a2_push_wallball_interference', 'main', 'wall_balls',
 '[{"exercise":"4 rounds — 90 s between rounds","rest_sec":90},{"exercise":"Sled push at race weight","distance_m":50,"load_by_division":{"open":"152 kg","pro":"202 kg"}},{"exercise":"Wall balls, unbroken","reps":30,"load_by_division":{"open":"6 kg","pro":"9 kg"}}]'::jsonb,
 'gym', 2, '{station_work}', '{station,advanced,build,wall_balls}'),
('558c80de-8e18-53eb-b20f-836e7a1506de', 'sw_a2_pull_grip_complex', 'main', 'sled_pull',
 '[{"exercise":"4 rounds — 90 s between rounds","rest_sec":90},{"exercise":"RowErg, sub 1:45 / 500 m","distance_m":500},{"exercise":"Sled pull at race weight","distance_m":50,"load_by_division":{"open":"103 kg","pro":"153 kg"}},{"exercise":"Farmers carry","distance_m":100,"load_by_division":{"open":"2×24 kg","pro":"2×32 kg"}}]'::jsonb,
 'gym', 2, '{station_work}', '{station,advanced,build,sled_pull}'),
('e6627339-32a5-580f-9033-418a5b8cbbee', 'sw_a2_locomotor_stamina', 'main', 'sandbag_lunges',
 '[{"exercise":"3 rounds — 2 min between rounds","rest_sec":120},{"exercise":"Sandbag lunges","distance_m":60,"load_by_division":{"open":"20 kg","pro":"30 kg"}},{"exercise":"Burpee broad jumps","reps":25}]'::jsonb,
 'gym', 2, '{station_work}', '{station,advanced,build,sandbag_lunges}'),
('7b02d46d-7ac2-512b-839a-17d9a554d63c', 'sw_a3_cardio_race_pace', 'main', 'row',
 '[{"exercise":"3 rounds — 3 min between rounds","rest_sec":180},{"exercise":"SkiErg at 3:45–3:55 / 1000 m","distance_m":1000},{"exercise":"RowErg at 3:45–3:55 / 1000 m","distance_m":1000}]'::jsonb,
 'gym', 2, '{station_work}', '{station,advanced,peak,row}'),
('005f27a0-c281-58f7-a9e9-f7a911c5cc3e', 'sw_a3_resistance_triad', 'main', 'sled_push',
 '[{"exercise":"3 rounds — 2 min between rounds","rest_sec":120},{"exercise":"Sled push at race weight","distance_m":50,"load_by_division":{"open":"152 kg","pro":"202 kg"}},{"exercise":"Sled pull at race weight","distance_m":50,"load_by_division":{"open":"103 kg","pro":"153 kg"}},{"exercise":"Sandbag lunges at race weight","distance_m":100,"load_by_division":{"open":"20 kg","pro":"30 kg"}}]'::jsonb,
 'gym', 2, '{station_work}', '{station,advanced,peak,sled_push}'),
('9668f3bc-962b-5b22-9a00-fcc0bad6eef3', 'sw_a3_burnout_finisher', 'main', 'wall_balls',
 '[{"exercise":"4 rounds — 90 s between rounds","rest_sec":90},{"exercise":"Burpee broad jumps","reps":25},{"exercise":"Wall balls at race weight, unbroken","reps":35,"load_by_division":{"open":"6 kg","pro":"9 kg"}}]'::jsonb,
 'gym', 2, '{station_work}', '{station,advanced,peak,wall_balls}'),
('e95418bd-2f8c-5e88-b35e-92b273bb7450', 'sw_a4_pace_precision', 'main', 'ski_erg',
 '[{"exercise":"3 rounds — 2 min between rounds","rest_sec":120},{"exercise":"SkiErg at race pace","distance_m":250},{"exercise":"Sled push at race weight","distance_m":12.5,"load_by_division":{"open":"152 kg","pro":"202 kg"}}]'::jsonb,
 'gym', 2, '{station_work}', '{station,advanced,taper,ski_erg}'),
('18a1d02c-7250-5aee-982b-9a098a15be8e', 'sw_a4_match_speed_balls', 'main', 'wall_balls',
 '[{"exercise":"2 rounds"},{"exercise":"RowErg","distance_m":250},{"exercise":"Wall balls at match speed","reps":15,"load_by_division":{"open":"6 kg","pro":"9 kg"}}]'::jsonb,
 'gym', 2, '{station_work}', '{station,advanced,taper,wall_balls}'),
('74ad923b-7b68-5562-9c26-96c386136b88', 'sw_a4_jump_carry_activation', 'main', 'burpee_broad_jump',
 '[{"exercise":"3 rounds"},{"exercise":"Burpee broad jumps, explosive","reps":4},{"exercise":"Farmers carry","distance_m":20,"load_by_division":{"open":"2×24 kg","pro":"2×32 kg"}}]'::jsonb,
 'gym', 2, '{station_work}', '{station,advanced,taper,burpee_broad_jump}'),
('e185bf56-34d9-5e9f-9ad0-e238917bada3', 'sw_e1_aerobic_engine', 'main', 'ski_erg',
 '[{"exercise":"SkiErg, strictly below LT1 — 10 min"},{"exercise":"RowErg, strictly below LT1 — 10 min"},{"exercise":"Echo bike or equivalent, strictly below LT1 — 10 min"},{"exercise":"SkiErg, strictly below LT1 — 10 min"}]'::jsonb,
 'gym', 3, '{station_work}', '{station,elite,base,ski_erg}'),
('8d6edd34-f1a9-5967-87fb-1d74e10ecc78', 'sw_e1_heavy_resistance_overload', 'main', 'sled_push',
 '[{"exercise":"6 rounds — 2 min between rounds","rest_sec":120},{"exercise":"Sled push, race weight +30 kg","distance_m":25,"load_by_division":{"open":"182 kg","pro":"232 kg"}},{"exercise":"Sled pull, race weight +20 kg","distance_m":25,"load_by_division":{"open":"123 kg","pro":"173 kg"}}]'::jsonb,
 'gym', 3, '{station_work}', '{station,elite,base,sled_push}'),
('f23b46e3-d43e-54e2-81e1-f60cc63836fd', 'sw_e1_grip_posterior_endurance', 'main', 'farmers_carry',
 '[{"exercise":"5 rounds — 90 s between rounds","rest_sec":90},{"exercise":"Farmers carry, heavy","distance_m":100,"load_by_division":{"open":"2×32 kg","pro":"2×32 kg"}},{"exercise":"Sandbag lunges","distance_m":40,"load_by_division":{"open":"30 kg","pro":"30 kg"}}]'::jsonb,
 'gym', 3, '{station_work}', '{station,elite,base,farmers_carry}'),
('412bb939-db65-524f-8a01-d60222fa3936', 'sw_e2_station_cluster_one', 'main', 'sled_push',
 '[{"exercise":"4 rounds — 90 s between rounds","rest_sec":90},{"exercise":"SkiErg, sub 1:48 / 500 m","distance_m":500},{"exercise":"Sled push at race weight — 25 m out, 25 m back","distance_m":50,"load_by_division":{"open":"152 kg","pro":"202 kg"}},{"exercise":"Sled pull at race weight, hand over hand","distance_m":50,"load_by_division":{"open":"103 kg","pro":"153 kg"}},{"exercise":"Sandbag lunges","distance_m":40,"load_by_division":{"open":"20 kg","pro":"30 kg"}}]'::jsonb,
 'gym', 3, '{station_work}', '{station,elite,build,sled_push}'),
('9d033fc0-e85e-50da-bc19-eb976fc97bc1', 'sw_e2_station_cluster_two', 'main', 'wall_balls',
 '[{"exercise":"4 rounds — 90 s between rounds","rest_sec":90},{"exercise":"RowErg, sub 1:45 / 500 m","distance_m":500},{"exercise":"Burpee broad jumps — keep one rhythm","reps":25},{"exercise":"Farmers carry","distance_m":100,"load_by_division":{"open":"2×24 kg","pro":"2×32 kg"}},{"exercise":"Wall balls","reps":30,"load_by_division":{"open":"6 kg","pro":"9 kg"}}]'::jsonb,
 'gym', 3, '{station_work}', '{station,elite,build,wall_balls}'),
('d7d84c15-6432-5493-ae6c-e15800412efb', 'sw_e2_lactate_sled_erg', 'main', 'sled_pull',
 '[{"exercise":"5 rounds — 2 min between rounds","rest_sec":120},{"exercise":"SkiErg, all out","distance_m":250},{"exercise":"Sled push at race pace","distance_m":25,"load_by_division":{"open":"152 kg","pro":"202 kg"}},{"exercise":"RowErg, all out — straight on","distance_m":250},{"exercise":"Sled pull at race weight","distance_m":25,"load_by_division":{"open":"103 kg","pro":"153 kg"}}]'::jsonb,
 'gym', 3, '{station_work}', '{station,elite,build,sled_pull}'),
('caa6ac22-a8ee-5e86-a513-5295de3d2793', 'sw_e3_erg_wallball_density', 'main', 'wall_balls',
 '[{"exercise":"3 rounds — 2 min between rounds","rest_sec":120},{"exercise":"SkiErg at race pace, 3:45–3:55 / 1000 m","distance_m":1000},{"exercise":"RowErg at race pace, 3:45–3:55 / 1000 m","distance_m":1000},{"exercise":"Wall balls, unbroken","reps":40,"load_by_division":{"open":"6 kg","pro":"9 kg"}}]'::jsonb,
 'gym', 3, '{station_work}', '{station,elite,peak,wall_balls}'),
('897603b6-08fe-590d-82fe-8821dadb8533', 'sw_e3_resistance_gauntlet', 'main', 'sled_pull',
 '[{"exercise":"2 rounds — 3 min between rounds","rest_sec":180},{"exercise":"Sled push at race weight","distance_m":50,"load_by_division":{"open":"152 kg","pro":"202 kg"},"rest_sec":15},{"exercise":"Sled pull at race weight","distance_m":50,"load_by_division":{"open":"103 kg","pro":"153 kg"},"rest_sec":15},{"exercise":"Sandbag lunges","distance_m":100,"load_by_division":{"open":"20 kg","pro":"30 kg"},"rest_sec":15},{"exercise":"Farmers carry","distance_m":200,"load_by_division":{"open":"2×24 kg","pro":"2×32 kg"}}]'::jsonb,
 'gym', 3, '{station_work}', '{station,elite,peak,sled_pull}'),
('4a4327b5-a728-55c5-8224-9cde919a61f2', 'sw_e3_burpee_wallball_climax', 'main', 'burpee_broad_jump',
 '[{"exercise":"3 rounds — 3 min between rounds","rest_sec":180},{"exercise":"Burpee broad jumps","distance_m":80},{"exercise":"Wall balls at race weight, unbroken","reps":50,"load_by_division":{"open":"6 kg","pro":"9 kg"}}]'::jsonb,
 'gym', 3, '{station_work}', '{station,elite,peak,burpee_broad_jump}'),
('fe6d57ff-8dce-5e7c-a62e-2544042df695', 'sw_e4_sharpening_ski_push', 'main', 'ski_erg',
 '[{"exercise":"3 rounds — 90 s between rounds","rest_sec":90},{"exercise":"SkiErg at race pace","distance_m":250},{"exercise":"Sled push at race weight","distance_m":12.5,"load_by_division":{"open":"152 kg","pro":"202 kg"}}]'::jsonb,
 'gym', 3, '{station_work}', '{station,elite,taper,ski_erg}'),
('4b251fb0-8782-5951-9b83-e15159a65f28', 'sw_e4_breathing_rhythm', 'main', 'wall_balls',
 '[{"exercise":"2 rounds"},{"exercise":"RowErg, smooth","distance_m":250},{"exercise":"Wall balls, unbroken — breathe on the catch","reps":20,"load_by_division":{"open":"6 kg","pro":"9 kg"}}]'::jsonb,
 'gym', 3, '{station_work}', '{station,elite,taper,wall_balls}'),
('48ee54ea-2c37-5b57-9cfa-54351075b733', 'sw_e4_explosive_activation', 'main', 'burpee_broad_jump',
 '[{"exercise":"4 rounds"},{"exercise":"Broad jumps, explosive — no burpee, full recovery","reps":3},{"exercise":"Farmers walk, fast","distance_m":20,"load_by_division":{"open":"2×24 kg","pro":"2×32 kg"}}]'::jsonb,
 'gym', 3, '{station_work}', '{station,elite,taper,burpee_broad_jump}'),
('4fa121e2-9fd0-516e-bec3-8e3ba173a4ba', 'sw_w1_erg_threshold_volume', 'main', 'ski_erg',
 '[{"exercise":"8 rounds — 45 s between rounds","rest_sec":45},{"exercise":"SkiErg, sub 1:42 / 500 m — active rest between","distance_m":500}]'::jsonb,
 'gym', 3, '{station_work}', '{station,world_class,base,ski_erg}'),
('f98452d2-101b-5fa1-ad7f-ca3e34bc4dfa', 'sw_w1_extreme_sled_overload', 'main', 'sled_push',
 '[{"exercise":"6 rounds — 150 s between rounds","rest_sec":150},{"exercise":"Sled push, at or above pro race weight","distance_m":20,"load_by_division":{"open":"202 kg","pro":"252 kg"}},{"exercise":"Heavy rope pull — maximum tension, hand over hand","distance_m":20,"load_by_division":{"open":"133 kg","pro":"183 kg"}}]'::jsonb,
 'gym', 3, '{station_work}', '{station,world_class,base,sled_push}'),
('46579852-bf22-5af7-a44d-7c1f5792fc6d', 'sw_w1_fatigue_buffer', 'main', 'sandbag_lunges',
 '[{"exercise":"5 rounds — 90 s between rounds","rest_sec":90},{"exercise":"Sandbag lunges","distance_m":60,"load_by_division":{"open":"30 kg","pro":"30 kg"}},{"exercise":"Farmers carry, heavy","distance_m":100,"load_by_division":{"open":"2×36 kg","pro":"2×36 kg"}},{"exercise":"Weighted squats","reps":30,"load_by_division":{"open":"32 kg","pro":"40 kg"}}]'::jsonb,
 'gym', 3, '{station_work}', '{station,world_class,base,sandbag_lunges}'),
('33cf657f-6d81-56da-bd16-430018ffcfc1', 'sw_w2_maximal_split_resistance', 'main', 'sled_push',
 '[{"exercise":"5 rounds — 1 min between rounds","rest_sec":60},{"exercise":"Sled push at pro weight, sub 1:15","distance_m":50,"load_by_division":{"open":"202 kg","pro":"202 kg"}},{"exercise":"Sled pull, sub 1:20","distance_m":50,"load_by_division":{"open":"103 kg","pro":"153 kg"}},{"exercise":"Wall balls, unbroken","reps":30,"load_by_division":{"open":"9 kg","pro":"9 kg"}}]'::jsonb,
 'gym', 3, '{station_work}', '{station,world_class,build,sled_push}'),
('824deed9-d862-5081-90da-4282aad39511', 'sw_w2_ergometer_acidosis', 'main', 'sled_pull',
 '[{"exercise":"4 rounds — 2 min between rounds","rest_sec":120},{"exercise":"SkiErg, sub 1:38 / 500 m","distance_m":750},{"exercise":"Sled pull at race weight","distance_m":50,"load_by_division":{"open":"103 kg","pro":"153 kg"}},{"exercise":"RowErg, sub 1:36 / 500 m","distance_m":750}]'::jsonb,
 'gym', 3, '{station_work}', '{station,world_class,build,sled_pull}'),
('8ba7a6ad-e279-55b6-80d3-4b2cb52e12a5', 'sw_w2_high_velocity_locomotion', 'main', 'burpee_broad_jump',
 '[{"exercise":"4 rounds — 2 min between rounds","rest_sec":120},{"exercise":"Burpee broad jumps, under 2:40","distance_m":80},{"exercise":"Sandbag lunges, under 3:15","distance_m":100,"load_by_division":{"open":"20 kg","pro":"30 kg"}}]'::jsonb,
 'gym', 3, '{station_work}', '{station,world_class,build,burpee_broad_jump}'),
('1f6021ff-3f44-5f56-b488-5580fed7ceec', 'sw_w3_erg_race_simulation', 'main', 'wall_balls',
 '[{"exercise":"2 rounds — 2 min between rounds","rest_sec":120},{"exercise":"SkiErg at race pace, sub 3:35 / 1000 m","distance_m":1000},{"exercise":"RowErg at race pace, sub 3:35 / 1000 m","distance_m":1000},{"exercise":"Wall balls, unbroken","reps":50,"load_by_division":{"open":"9 kg","pro":"9 kg"}}]'::jsonb,
 'gym', 3, '{station_work}', '{station,world_class,peak,wall_balls}'),
('4c763652-1f81-5fe2-a035-f76bd6d660b9', 'sw_w3_heavy_station_lockout', 'main', 'sled_push',
 '[{"exercise":"Sled push at race weight","distance_m":50,"load_by_division":{"open":"152 kg","pro":"202 kg"}},{"exercise":"Sled pull at race weight — no rest","distance_m":50,"load_by_division":{"open":"103 kg","pro":"153 kg"}},{"exercise":"Farmers carry — no rest","distance_m":200,"load_by_division":{"open":"2×24 kg","pro":"2×32 kg"}},{"exercise":"Sandbag lunges — no rest","distance_m":100,"load_by_division":{"open":"20 kg","pro":"30 kg"}}]'::jsonb,
 'gym', 3, '{station_work}', '{station,world_class,peak,sled_push}'),
('8e0faff7-8dd3-5603-ad90-dbdee1b65c4a', 'sw_w3_metabolic_capacity_cap', 'main', 'wall_balls',
 '[{"exercise":"Wall balls, unbroken, for time","reps":100,"load_by_division":{"open":"9 kg","pro":"9 kg"},"rest_sec":180},{"exercise":"Burpee broad jumps, all out","distance_m":80}]'::jsonb,
 'gym', 3, '{station_work}', '{station,world_class,peak,wall_balls}'),
('744e23f3-a158-5593-bae2-5128843f50b8', 'sw_w4_ski_push_tune', 'main', 'ski_erg',
 '[{"exercise":"2 rounds"},{"exercise":"SkiErg at race pace","distance_m":300},{"exercise":"Sled push at race weight","distance_m":12.5,"load_by_division":{"open":"152 kg","pro":"202 kg"}},{"exercise":"Wall balls","reps":15,"load_by_division":{"open":"9 kg","pro":"9 kg"},"rest_sec":240}]'::jsonb,
 'gym', 3, '{station_work}', '{station,world_class,taper,ski_erg}'),
('22961c9e-e587-53da-8eea-f7031d1de470', 'sw_w4_row_pull_tune', 'main', 'sled_pull',
 '[{"exercise":"2 rounds"},{"exercise":"RowErg at race pace","distance_m":300},{"exercise":"Sled pull at race weight","distance_m":12.5,"load_by_division":{"open":"103 kg","pro":"153 kg"}},{"exercise":"Burpee broad jumps","reps":5}]'::jsonb,
 'gym', 3, '{station_work}', '{station,world_class,taper,sled_pull}'),
('ba40af17-2d3d-555c-9311-170139748a5b', 'sw_w4_reactivity_drills', 'main', 'farmers_carry',
 '[{"exercise":"3 rounds"},{"exercise":"Farmers carry at high tempo","distance_m":20,"load_by_division":{"open":"2×24 kg","pro":"2×32 kg"}},{"exercise":"Reactivity drills — pogo hops, short contacts, quick feet","reps":20}]'::jsonb,
 'gym', 3, '{station_work}', '{station,world_class,taper,farmers_carry}')
on conflict (slug) do update set
  content = excluded.content,
  station = excluded.station,
  difficulty_tier = excluded.difficulty_tier,
  session_types = excluded.session_types,
  tags = excluded.tags;
